version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/chonky"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/chonky-icon-fontawesome"
    schedule:
      interval: "daily"
